//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 10:54:08 PM EAT 
//


package com.kcbgroup.common.models.iprsresidentinfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HumanInfoFromAlienCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HumanInfoFromAlienCard">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.datacontract.org/2004/07/IPRSManager}HumanInfoCommon">
 *       &lt;sequence>
 *         &lt;element name="Date_of_Expiry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Date_of_Issue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegOffice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Serial_Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HumanInfoFromAlienCard", namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", propOrder = {
    "dateOfExpiry",
    "dateOfIssue",
    "regOffice",
    "serialNumber"
})
public class HumanInfoFromAlienCard
    extends HumanInfoCommon
{

    @XmlElementRef(name = "Date_of_Expiry", namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dateOfExpiry;
    @XmlElementRef(name = "Date_of_Issue", namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dateOfIssue;
    @XmlElementRef(name = "RegOffice", namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", type = JAXBElement.class, required = false)
    protected JAXBElement<String> regOffice;
    @XmlElementRef(name = "Serial_Number", namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", type = JAXBElement.class, required = false)
    protected JAXBElement<String> serialNumber;

    /**
     * Gets the value of the dateOfExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDateOfExpiry() {
        return dateOfExpiry;
    }

    /**
     * Sets the value of the dateOfExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDateOfExpiry(JAXBElement<String> value) {
        this.dateOfExpiry = value;
    }

    /**
     * Gets the value of the dateOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDateOfIssue() {
        return dateOfIssue;
    }

    /**
     * Sets the value of the dateOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDateOfIssue(JAXBElement<String> value) {
        this.dateOfIssue = value;
    }

    /**
     * Gets the value of the regOffice property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegOffice() {
        return regOffice;
    }

    /**
     * Sets the value of the regOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegOffice(JAXBElement<String> value) {
        this.regOffice = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSerialNumber(JAXBElement<String> value) {
        this.serialNumber = value;
    }

}
