//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 10:54:08 PM EAT 
//


package com.kcbgroup.common.models.iprsresidentinfo;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kcbgroup.mapper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _ArrayOfbase64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfbase64Binary");
    private final static QName _HumanInfoFromIDCard_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "HumanInfoFromIDCard");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _HumanInfoFromPassport_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "HumanInfoFromPassport");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _CustomError_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "CustomError");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _HumanInfoFromAlienCard_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "HumanInfoFromAlienCard");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _HumanInfoCommon_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "HumanInfoCommon");
    private final static QName _FingerprintVerificationResult_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "FingerprintVerificationResult");
    private final static QName _FingerprintVerificationResultsSet_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "FingerprintVerificationResultsSet");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _VerificationByIdCardIdNumber_QNAME = new QName("http://tempuri.org/", "id_number");
    private final static QName _VerificationByIdCardLog_QNAME = new QName("http://tempuri.org/", "log");
    private final static QName _VerificationByIdCardPass_QNAME = new QName("http://tempuri.org/", "pass");
    private final static QName _VerificationByIdCardSerialNumber_QNAME = new QName("http://tempuri.org/", "serial_number");
    private final static QName _VerificationByIdCardFingerprints_QNAME = new QName("http://tempuri.org/", "fingerprints");
    private final static QName _VerificationByIdCardResponseVerificationByIdCardResult_QNAME = new QName("http://tempuri.org/", "VerificationByIdCardResult");
    private final static QName _GetDataByPassportPassportNumber_QNAME = new QName("http://tempuri.org/", "passport_number");
    private final static QName _GetDataByIdCardResponseGetDataByIdCardResult_QNAME = new QName("http://tempuri.org/", "GetDataByIdCardResult");
    private final static QName _HumanInfoCommonIDNumber_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "ID_Number");
    private final static QName _HumanInfoCommonPlaceOfBirth_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Place_of_Birth");
    private final static QName _HumanInfoCommonGender_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Gender");
    private final static QName _HumanInfoCommonPhoto_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Photo");
    private final static QName _HumanInfoCommonCitizenship_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Citizenship");
    private final static QName _HumanInfoCommonDateOfBirth_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Date_of_Birth");
    private final static QName _HumanInfoCommonFingerprint_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Fingerprint");
    private final static QName _HumanInfoCommonPlaceOfLive_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Place_of_Live");
    private final static QName _HumanInfoCommonSurname_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Surname");
    private final static QName _HumanInfoCommonFamily_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Family");
    private final static QName _HumanInfoCommonOtherName_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Other_Name");
    private final static QName _HumanInfoCommonPlaceOfDeath_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Place_of_Death");
    private final static QName _HumanInfoCommonDateOfDeath_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Date_of_Death");
    private final static QName _HumanInfoCommonSignature_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Signature");
    private final static QName _HumanInfoCommonClan_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Clan");
    private final static QName _HumanInfoCommonPin_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Pin");
    private final static QName _HumanInfoCommonEthnicGroup_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Ethnic_Group");
    private final static QName _HumanInfoCommonOccupation_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Occupation");
    private final static QName _HumanInfoCommonFirstName_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "First_Name");
    private final static QName _GetDataByAlienCardResponseGetDataByAlienCardResult_QNAME = new QName("http://tempuri.org/", "GetDataByAlienCardResult");
    private final static QName _HumanInfoFromAlienCardSerialNumber_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Serial_Number");
    private final static QName _HumanInfoFromAlienCardDateOfExpiry_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Date_of_Expiry");
    private final static QName _HumanInfoFromAlienCardDateOfIssue_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Date_of_Issue");
    private final static QName _HumanInfoFromAlienCardRegOffice_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "RegOffice");
    private final static QName _GetDataByPassportResponseGetDataByPassportResult_QNAME = new QName("http://tempuri.org/", "GetDataByPassportResult");
    private final static QName _VerificationByPassportResponseVerificationByPassportResult_QNAME = new QName("http://tempuri.org/", "VerificationByPassportResult");
    private final static QName _CustomErrorErrorMessage_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "ErrorMessage");
    private final static QName _CustomErrorErrorCode_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "ErrorCode");
    private final static QName _HumanInfoFromPassportPassportNumber_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Passport_Number");
    private final static QName _HumanInfoFromPassportDateOfBirthFromPassport_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Date_of_Birth_from_Passport");
    private final static QName _HumanInfoFromPassportPhotoFromPassport_QNAME = new QName("http://schemas.datacontract.org/2004/07/IPRSManager", "Photo_from_Passport");
    private final static QName _VerificationByAlienCardResponseVerificationByAlienCardResult_QNAME = new QName("http://tempuri.org/", "VerificationByAlienCardResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kcbgroup.mapper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VerificationByPassportResponse }
     * 
     */
    public VerificationByPassportResponse createVerificationByPassportResponse() {
        return new VerificationByPassportResponse();
    }

    /**
     * Create an instance of {@link FingerprintVerificationResult }
     * 
     */
    public FingerprintVerificationResult createFingerprintVerificationResult() {
        return new FingerprintVerificationResult();
    }

    /**
     * Create an instance of {@link VerificationByAlienCardResponse }
     * 
     */
    public VerificationByAlienCardResponse createVerificationByAlienCardResponse() {
        return new VerificationByAlienCardResponse();
    }

    /**
     * Create an instance of {@link VerificationByIdCard }
     * 
     */
    public VerificationByIdCard createVerificationByIdCard() {
        return new VerificationByIdCard();
    }

    /**
     * Create an instance of {@link ArrayOfbase64Binary }
     * 
     */
    public ArrayOfbase64Binary createArrayOfbase64Binary() {
        return new ArrayOfbase64Binary();
    }

    /**
     * Create an instance of {@link PingServiceResponse }
     * 
     */
    public PingServiceResponse createPingServiceResponse() {
        return new PingServiceResponse();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetDataByAlienCardResponse }
     * 
     */
    public GetDataByAlienCardResponse createGetDataByAlienCardResponse() {
        return new GetDataByAlienCardResponse();
    }

    /**
     * Create an instance of {@link HumanInfoFromAlienCard }
     * 
     */
    public HumanInfoFromAlienCard createHumanInfoFromAlienCard() {
        return new HumanInfoFromAlienCard();
    }

    /**
     * Create an instance of {@link VerificationByPassport }
     * 
     */
    public VerificationByPassport createVerificationByPassport() {
        return new VerificationByPassport();
    }

    /**
     * Create an instance of {@link VerificationByAlienCard }
     * 
     */
    public VerificationByAlienCard createVerificationByAlienCard() {
        return new VerificationByAlienCard();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link GetDataByPassportResponse }
     * 
     */
    public GetDataByPassportResponse createGetDataByPassportResponse() {
        return new GetDataByPassportResponse();
    }

    /**
     * Create an instance of {@link HumanInfoFromPassport }
     * 
     */
    public HumanInfoFromPassport createHumanInfoFromPassport() {
        return new HumanInfoFromPassport();
    }

    /**
     * Create an instance of {@link GetDataByAlienCard }
     * 
     */
    public GetDataByAlienCard createGetDataByAlienCard() {
        return new GetDataByAlienCard();
    }

    /**
     * Create an instance of {@link VerificationByIdCardResponse }
     * 
     */
    public VerificationByIdCardResponse createVerificationByIdCardResponse() {
        return new VerificationByIdCardResponse();
    }

    /**
     * Create an instance of {@link PingService }
     * 
     */
    public PingService createPingService() {
        return new PingService();
    }

    /**
     * Create an instance of {@link GetDataByIdCardResponse }
     * 
     */
    public GetDataByIdCardResponse createGetDataByIdCardResponse() {
        return new GetDataByIdCardResponse();
    }

    /**
     * Create an instance of {@link HumanInfoFromIDCard }
     * 
     */
    public HumanInfoFromIDCard createHumanInfoFromIDCard() {
        return new HumanInfoFromIDCard();
    }

    /**
     * Create an instance of {@link GetDataByPassport }
     * 
     */
    public GetDataByPassport createGetDataByPassport() {
        return new GetDataByPassport();
    }

    /**
     * Create an instance of {@link GetDataByIdCard }
     * 
     */
    public GetDataByIdCard createGetDataByIdCard() {
        return new GetDataByIdCard();
    }

    /**
     * Create an instance of {@link CustomError }
     * 
     */
    public CustomError createCustomError() {
        return new CustomError();
    }

    /**
     * Create an instance of {@link HumanInfoCommon }
     * 
     */
    public HumanInfoCommon createHumanInfoCommon() {
        return new HumanInfoCommon();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfbase64Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", name = "ArrayOfbase64Binary")
    public JAXBElement<ArrayOfbase64Binary> createArrayOfbase64Binary(ArrayOfbase64Binary value) {
        return new JAXBElement<ArrayOfbase64Binary>(_ArrayOfbase64Binary_QNAME, ArrayOfbase64Binary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoFromIDCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "HumanInfoFromIDCard")
    public JAXBElement<HumanInfoFromIDCard> createHumanInfoFromIDCard(HumanInfoFromIDCard value) {
        return new JAXBElement<HumanInfoFromIDCard>(_HumanInfoFromIDCard_QNAME, HumanInfoFromIDCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoFromPassport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "HumanInfoFromPassport")
    public JAXBElement<HumanInfoFromPassport> createHumanInfoFromPassport(HumanInfoFromPassport value) {
        return new JAXBElement<HumanInfoFromPassport>(_HumanInfoFromPassport_QNAME, HumanInfoFromPassport.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomError }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "CustomError")
    public JAXBElement<CustomError> createCustomError(CustomError value) {
        return new JAXBElement<CustomError>(_CustomError_QNAME, CustomError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoFromAlienCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "HumanInfoFromAlienCard")
    public JAXBElement<HumanInfoFromAlienCard> createHumanInfoFromAlienCard(HumanInfoFromAlienCard value) {
        return new JAXBElement<HumanInfoFromAlienCard>(_HumanInfoFromAlienCard_QNAME, HumanInfoFromAlienCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoCommon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "HumanInfoCommon")
    public JAXBElement<HumanInfoCommon> createHumanInfoCommon(HumanInfoCommon value) {
        return new JAXBElement<HumanInfoCommon>(_HumanInfoCommon_QNAME, HumanInfoCommon.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintVerificationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "FingerprintVerificationResult")
    public JAXBElement<FingerprintVerificationResult> createFingerprintVerificationResult(FingerprintVerificationResult value) {
        return new JAXBElement<FingerprintVerificationResult>(_FingerprintVerificationResult_QNAME, FingerprintVerificationResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintVerificationResultsSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "FingerprintVerificationResultsSet")
    public JAXBElement<FingerprintVerificationResultsSet> createFingerprintVerificationResultsSet(FingerprintVerificationResultsSet value) {
        return new JAXBElement<FingerprintVerificationResultsSet>(_FingerprintVerificationResultsSet_QNAME, FingerprintVerificationResultsSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "id_number", scope = VerificationByIdCard.class)
    public JAXBElement<String> createVerificationByIdCardIdNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardIdNumber_QNAME, String.class, VerificationByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = VerificationByIdCard.class)
    public JAXBElement<String> createVerificationByIdCardLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, VerificationByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = VerificationByIdCard.class)
    public JAXBElement<String> createVerificationByIdCardPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, VerificationByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "serial_number", scope = VerificationByIdCard.class)
    public JAXBElement<String> createVerificationByIdCardSerialNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardSerialNumber_QNAME, String.class, VerificationByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfbase64Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "fingerprints", scope = VerificationByIdCard.class)
    public JAXBElement<ArrayOfbase64Binary> createVerificationByIdCardFingerprints(ArrayOfbase64Binary value) {
        return new JAXBElement<ArrayOfbase64Binary>(_VerificationByIdCardFingerprints_QNAME, ArrayOfbase64Binary.class, VerificationByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintVerificationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "VerificationByIdCardResult", scope = VerificationByIdCardResponse.class)
    public JAXBElement<FingerprintVerificationResult> createVerificationByIdCardResponseVerificationByIdCardResult(FingerprintVerificationResult value) {
        return new JAXBElement<FingerprintVerificationResult>(_VerificationByIdCardResponseVerificationByIdCardResult_QNAME, FingerprintVerificationResult.class, VerificationByIdCardResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "id_number", scope = GetDataByPassport.class)
    public JAXBElement<String> createGetDataByPassportIdNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardIdNumber_QNAME, String.class, GetDataByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "passport_number", scope = GetDataByPassport.class)
    public JAXBElement<String> createGetDataByPassportPassportNumber(String value) {
        return new JAXBElement<String>(_GetDataByPassportPassportNumber_QNAME, String.class, GetDataByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = GetDataByPassport.class)
    public JAXBElement<String> createGetDataByPassportLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, GetDataByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = GetDataByPassport.class)
    public JAXBElement<String> createGetDataByPassportPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, GetDataByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "id_number", scope = GetDataByAlienCard.class)
    public JAXBElement<String> createGetDataByAlienCardIdNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardIdNumber_QNAME, String.class, GetDataByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = GetDataByAlienCard.class)
    public JAXBElement<String> createGetDataByAlienCardLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, GetDataByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = GetDataByAlienCard.class)
    public JAXBElement<String> createGetDataByAlienCardPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, GetDataByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "serial_number", scope = GetDataByAlienCard.class)
    public JAXBElement<String> createGetDataByAlienCardSerialNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardSerialNumber_QNAME, String.class, GetDataByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoFromIDCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetDataByIdCardResult", scope = GetDataByIdCardResponse.class)
    public JAXBElement<HumanInfoFromIDCard> createGetDataByIdCardResponseGetDataByIdCardResult(HumanInfoFromIDCard value) {
        return new JAXBElement<HumanInfoFromIDCard>(_GetDataByIdCardResponseGetDataByIdCardResult_QNAME, HumanInfoFromIDCard.class, GetDataByIdCardResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "ID_Number", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonIDNumber(String value) {
        return new JAXBElement<String>(_HumanInfoCommonIDNumber_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Place_of_Birth", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonPlaceOfBirth(String value) {
        return new JAXBElement<String>(_HumanInfoCommonPlaceOfBirth_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Gender", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonGender(String value) {
        return new JAXBElement<String>(_HumanInfoCommonGender_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Photo", scope = HumanInfoCommon.class)
    public JAXBElement<byte[]> createHumanInfoCommonPhoto(byte[] value) {
        return new JAXBElement<byte[]>(_HumanInfoCommonPhoto_QNAME, byte[].class, HumanInfoCommon.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Citizenship", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonCitizenship(String value) {
        return new JAXBElement<String>(_HumanInfoCommonCitizenship_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Birth", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonDateOfBirth(String value) {
        return new JAXBElement<String>(_HumanInfoCommonDateOfBirth_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Fingerprint", scope = HumanInfoCommon.class)
    public JAXBElement<byte[]> createHumanInfoCommonFingerprint(byte[] value) {
        return new JAXBElement<byte[]>(_HumanInfoCommonFingerprint_QNAME, byte[].class, HumanInfoCommon.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Place_of_Live", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonPlaceOfLive(String value) {
        return new JAXBElement<String>(_HumanInfoCommonPlaceOfLive_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Surname", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonSurname(String value) {
        return new JAXBElement<String>(_HumanInfoCommonSurname_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Family", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonFamily(String value) {
        return new JAXBElement<String>(_HumanInfoCommonFamily_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Other_Name", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonOtherName(String value) {
        return new JAXBElement<String>(_HumanInfoCommonOtherName_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Place_of_Death", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonPlaceOfDeath(String value) {
        return new JAXBElement<String>(_HumanInfoCommonPlaceOfDeath_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Death", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonDateOfDeath(String value) {
        return new JAXBElement<String>(_HumanInfoCommonDateOfDeath_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Signature", scope = HumanInfoCommon.class)
    public JAXBElement<byte[]> createHumanInfoCommonSignature(byte[] value) {
        return new JAXBElement<byte[]>(_HumanInfoCommonSignature_QNAME, byte[].class, HumanInfoCommon.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Clan", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonClan(String value) {
        return new JAXBElement<String>(_HumanInfoCommonClan_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Pin", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonPin(String value) {
        return new JAXBElement<String>(_HumanInfoCommonPin_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Ethnic_Group", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonEthnicGroup(String value) {
        return new JAXBElement<String>(_HumanInfoCommonEthnicGroup_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Occupation", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonOccupation(String value) {
        return new JAXBElement<String>(_HumanInfoCommonOccupation_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "First_Name", scope = HumanInfoCommon.class)
    public JAXBElement<String> createHumanInfoCommonFirstName(String value) {
        return new JAXBElement<String>(_HumanInfoCommonFirstName_QNAME, String.class, HumanInfoCommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = Login.class)
    public JAXBElement<String> createLoginLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = Login.class)
    public JAXBElement<String> createLoginPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoFromAlienCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetDataByAlienCardResult", scope = GetDataByAlienCardResponse.class)
    public JAXBElement<HumanInfoFromAlienCard> createGetDataByAlienCardResponseGetDataByAlienCardResult(HumanInfoFromAlienCard value) {
        return new JAXBElement<HumanInfoFromAlienCard>(_GetDataByAlienCardResponseGetDataByAlienCardResult_QNAME, HumanInfoFromAlienCard.class, GetDataByAlienCardResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Serial_Number", scope = HumanInfoFromAlienCard.class)
    public JAXBElement<String> createHumanInfoFromAlienCardSerialNumber(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardSerialNumber_QNAME, String.class, HumanInfoFromAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Expiry", scope = HumanInfoFromAlienCard.class)
    public JAXBElement<String> createHumanInfoFromAlienCardDateOfExpiry(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardDateOfExpiry_QNAME, String.class, HumanInfoFromAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Issue", scope = HumanInfoFromAlienCard.class)
    public JAXBElement<String> createHumanInfoFromAlienCardDateOfIssue(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardDateOfIssue_QNAME, String.class, HumanInfoFromAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "RegOffice", scope = HumanInfoFromAlienCard.class)
    public JAXBElement<String> createHumanInfoFromAlienCardRegOffice(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardRegOffice_QNAME, String.class, HumanInfoFromAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "id_number", scope = GetDataByIdCard.class)
    public JAXBElement<String> createGetDataByIdCardIdNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardIdNumber_QNAME, String.class, GetDataByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = GetDataByIdCard.class)
    public JAXBElement<String> createGetDataByIdCardLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, GetDataByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = GetDataByIdCard.class)
    public JAXBElement<String> createGetDataByIdCardPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, GetDataByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "serial_number", scope = GetDataByIdCard.class)
    public JAXBElement<String> createGetDataByIdCardSerialNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardSerialNumber_QNAME, String.class, GetDataByIdCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "id_number", scope = VerificationByAlienCard.class)
    public JAXBElement<String> createVerificationByAlienCardIdNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardIdNumber_QNAME, String.class, VerificationByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = VerificationByAlienCard.class)
    public JAXBElement<String> createVerificationByAlienCardLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, VerificationByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = VerificationByAlienCard.class)
    public JAXBElement<String> createVerificationByAlienCardPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, VerificationByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "serial_number", scope = VerificationByAlienCard.class)
    public JAXBElement<String> createVerificationByAlienCardSerialNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardSerialNumber_QNAME, String.class, VerificationByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfbase64Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "fingerprints", scope = VerificationByAlienCard.class)
    public JAXBElement<ArrayOfbase64Binary> createVerificationByAlienCardFingerprints(ArrayOfbase64Binary value) {
        return new JAXBElement<ArrayOfbase64Binary>(_VerificationByIdCardFingerprints_QNAME, ArrayOfbase64Binary.class, VerificationByAlienCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HumanInfoFromPassport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetDataByPassportResult", scope = GetDataByPassportResponse.class)
    public JAXBElement<HumanInfoFromPassport> createGetDataByPassportResponseGetDataByPassportResult(HumanInfoFromPassport value) {
        return new JAXBElement<HumanInfoFromPassport>(_GetDataByPassportResponseGetDataByPassportResult_QNAME, HumanInfoFromPassport.class, GetDataByPassportResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Serial_Number", scope = HumanInfoFromIDCard.class)
    public JAXBElement<String> createHumanInfoFromIDCardSerialNumber(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardSerialNumber_QNAME, String.class, HumanInfoFromIDCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Issue", scope = HumanInfoFromIDCard.class)
    public JAXBElement<String> createHumanInfoFromIDCardDateOfIssue(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardDateOfIssue_QNAME, String.class, HumanInfoFromIDCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "RegOffice", scope = HumanInfoFromIDCard.class)
    public JAXBElement<String> createHumanInfoFromIDCardRegOffice(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardRegOffice_QNAME, String.class, HumanInfoFromIDCard.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintVerificationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "VerificationByPassportResult", scope = VerificationByPassportResponse.class)
    public JAXBElement<FingerprintVerificationResult> createVerificationByPassportResponseVerificationByPassportResult(FingerprintVerificationResult value) {
        return new JAXBElement<FingerprintVerificationResult>(_VerificationByPassportResponseVerificationByPassportResult_QNAME, FingerprintVerificationResult.class, VerificationByPassportResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "ErrorMessage", scope = CustomError.class)
    public JAXBElement<String> createCustomErrorErrorMessage(String value) {
        return new JAXBElement<String>(_CustomErrorErrorMessage_QNAME, String.class, CustomError.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "ErrorCode", scope = CustomError.class)
    public JAXBElement<String> createCustomErrorErrorCode(String value) {
        return new JAXBElement<String>(_CustomErrorErrorCode_QNAME, String.class, CustomError.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "id_number", scope = VerificationByPassport.class)
    public JAXBElement<String> createVerificationByPassportIdNumber(String value) {
        return new JAXBElement<String>(_VerificationByIdCardIdNumber_QNAME, String.class, VerificationByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "passport_number", scope = VerificationByPassport.class)
    public JAXBElement<String> createVerificationByPassportPassportNumber(String value) {
        return new JAXBElement<String>(_GetDataByPassportPassportNumber_QNAME, String.class, VerificationByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "log", scope = VerificationByPassport.class)
    public JAXBElement<String> createVerificationByPassportLog(String value) {
        return new JAXBElement<String>(_VerificationByIdCardLog_QNAME, String.class, VerificationByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "pass", scope = VerificationByPassport.class)
    public JAXBElement<String> createVerificationByPassportPass(String value) {
        return new JAXBElement<String>(_VerificationByIdCardPass_QNAME, String.class, VerificationByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfbase64Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "fingerprints", scope = VerificationByPassport.class)
    public JAXBElement<ArrayOfbase64Binary> createVerificationByPassportFingerprints(ArrayOfbase64Binary value) {
        return new JAXBElement<ArrayOfbase64Binary>(_VerificationByIdCardFingerprints_QNAME, ArrayOfbase64Binary.class, VerificationByPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Passport_Number", scope = HumanInfoFromPassport.class)
    public JAXBElement<String> createHumanInfoFromPassportPassportNumber(String value) {
        return new JAXBElement<String>(_HumanInfoFromPassportPassportNumber_QNAME, String.class, HumanInfoFromPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Birth_from_Passport", scope = HumanInfoFromPassport.class)
    public JAXBElement<String> createHumanInfoFromPassportDateOfBirthFromPassport(String value) {
        return new JAXBElement<String>(_HumanInfoFromPassportDateOfBirthFromPassport_QNAME, String.class, HumanInfoFromPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Photo_from_Passport", scope = HumanInfoFromPassport.class)
    public JAXBElement<byte[]> createHumanInfoFromPassportPhotoFromPassport(byte[] value) {
        return new JAXBElement<byte[]>(_HumanInfoFromPassportPhotoFromPassport_QNAME, byte[].class, HumanInfoFromPassport.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Expiry", scope = HumanInfoFromPassport.class)
    public JAXBElement<String> createHumanInfoFromPassportDateOfExpiry(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardDateOfExpiry_QNAME, String.class, HumanInfoFromPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/IPRSManager", name = "Date_of_Issue", scope = HumanInfoFromPassport.class)
    public JAXBElement<String> createHumanInfoFromPassportDateOfIssue(String value) {
        return new JAXBElement<String>(_HumanInfoFromAlienCardDateOfIssue_QNAME, String.class, HumanInfoFromPassport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintVerificationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "VerificationByAlienCardResult", scope = VerificationByAlienCardResponse.class)
    public JAXBElement<FingerprintVerificationResult> createVerificationByAlienCardResponseVerificationByAlienCardResult(FingerprintVerificationResult value) {
        return new JAXBElement<FingerprintVerificationResult>(_VerificationByAlienCardResponseVerificationByAlienCardResult_QNAME, FingerprintVerificationResult.class, VerificationByAlienCardResponse.class, value);
    }

}
